os: linux
dist: focal
language: python

python:
  - 3.8

install:
  - sudo apt -y install python3-distutils
  - sudo apt -y install python3-pip
  - sudo apt install -y git
  - git clone https://github.com/kivy/buildozer.git
  - python3 -m site
  - ls -l
  - cd buildozer
  - ls -l
  - python3 setup.py install
  - ls -l
  - cd ..
  - ls -l

  - sudo apt update
  - sudo apt-get install apt-utils
  - sudo sed -i.bak 's/us-west-2\.ec2\.//' /etc/apt/sources.list
  - sudo apt-get install build-essential python-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libjpeg-dev libpng-dev virtualenvwrapper
  - sudo apt install -y git zip unzip openjdk-8-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
  - pip3 install --upgrade Cython==0.29.19 virtualenv
  - export PATH=$PATH:~/.local/bin/
  - ls -l
  - git clone https://github.com/renpy/pygame_sdl2.git
  - cd pygame_sdl2
  - python3 setup.py install
  - cd ..
  - echo "TODO COMPILE 64bit"
  - ls -l /home/travis/
  - ls -l /home/travis/build/LORD-ME-CODE/govnogame/
  - ls -la
  - rm -r -f .buildozer
  - ls -la
  - rm -r -f /home/travis/build/LORD-ME-CODE/govnogame/.buildozer
  - ls -l /home/travis/
  - ls -l /home/travis/build/LORD-ME-CODE/govnogame/
  - ls -l
  - yes | cp -f buildozer-64bit.spec buildozer.spec
  - yes | buildozer android debug
  - ls -la
  - ls bin/ -l
  - echo "TODO"
  - gem install dpl --pre
  - dpl releases --token $GITHUB_TOKEN --file "bin/squidgame-0.3-arm64-v8a-debug.apk" --tag_name "v.0.1"
  - echo "OK"
